id: P71171190
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: Tibetan
  author: ''
created_at: '2022-01-14T19:24:59.484177'
last_modified_at: '2022-01-14T19:24:59.484182'
