id:
  P33565DA4:
    type: origin_type
    relation: translation
    language: Sanskrit
  PCA4BC641:
    type: origin_type
    relation: translation
    language: Chinese
  P5F84AB18:
    type: origin_type
    relation: translation
    language: Chinese
  P65FC7A9D:
    type: origin_type
    relation: translation
    language: Tibetan
  P12DA2985:
    type: origin_type
    relation: translation
    language: Tibetan
  PE17A895A:
    type: origin_type
    relation: translation
    language: English
title: 'Chapter 5: Caturbrahmavihāra'
type: translation
source_metadata:
  language:
  - Tibetan
  - Sanskrit
  - Chinese
  - English
