id:
  PDC844ECD:
    type: origin_type
    relation: translation
    language: Sanskrit
  P892D73DE:
    type: origin_type
    relation: translation
    language: Chinese
  P66170373:
    type: origin_type
    relation: translation
    language: Chinese
  P55E00DD5:
    type: origin_type
    relation: translation
    language: Tibetan
  PCD4BB3A5:
    type: origin_type
    relation: translation
    language: Tibetan
  P54ABD17B:
    type: origin_type
    relation: translation
    language: English
title: 'Chapter 9: Vīryapāramitā'
type: translation
source_metadata:
  language:
  - Tibetan
  - Sanskrit
  - English
  - Chinese
