id:
  PC4D0D824:
    type: origin_type
    relation: translation
    language: Sanskrit
  P4F4C6627:
    type: origin_type
    relation: translation
    language: Chinese
  PFD684F77:
    type: origin_type
    relation: translation
    language: Chinese
  PD9D55D2F:
    type: origin_type
    relation: translation
    language: Tibetan
  P4DA6D63C:
    type: origin_type
    relation: translation
    language: Tibetan
  PBAAD1EBF:
    type: origin_type
    relation: translation
    language: English
title: 'Chapter 1: Gṛhapati_Folio 5b'
type: translation
source_metadata:
  language:
  - Tibetan
  - Chinese
  - Sanskrit
  - English
