id: P8A51DD26
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: Chinese
  author: ''
created_at: '2022-01-14T19:24:59.482184'
last_modified_at: '2022-01-14T19:24:59.482192'
