id: PD55A37FF
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: Tibetan
  author: ''
created_at: '2022-02-17T10:27:08.937672'
last_modified_at: '2022-02-17T10:27:08.937674'
