id: PE7175F7F
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: Tibetan
  author: ''
created_at: '2022-01-14T19:24:59.484802'
last_modified_at: '2022-01-14T19:24:59.484807'
