id: PD48E0226
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: Chinese
  author: ''
created_at: '2022-02-17T10:27:08.936988'
last_modified_at: '2022-02-17T10:27:08.936991'
