id: PE2DCE7CE
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: Sanskrit
  author: ''
created_at: '2022-01-14T19:24:59.480560'
last_modified_at: '2022-01-14T19:24:59.480569'
