id: PFE5772A2
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: Tibetan
  author: ''
created_at: '2022-02-17T10:27:08.937333'
last_modified_at: '2022-02-17T10:27:08.937335'
