id: PD366116F
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: English
  author: ''
created_at: '2022-01-14T19:24:59.485482'
last_modified_at: '2022-01-14T19:24:59.485492'
