id:
  P3458ADB1:
    type: origin_type
    relation: translation
    language: Sanskrit
  PFBDA2CA5:
    type: origin_type
    relation: translation
    language: Chinese
  PE422C6FA:
    type: origin_type
    relation: translation
    language: Chinese
  P6AAA7A4A:
    type: origin_type
    relation: translation
    language: Tibetan
  P140B516B:
    type: origin_type
    relation: translation
    language: Tibetan
  P00189FF1:
    type: origin_type
    relation: translation
    language: English
title: 'Chapter 5: Caturbrahmavihāra'
type: translation
source_metadata:
  language:
  - English
  - Sanskrit
  - Chinese
  - Tibetan
