id: P33F8DD83
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: Chinese
  author: ''
created_at: '2022-02-17T10:27:08.936654'
last_modified_at: '2022-02-17T10:27:08.936657'
