id: PB4F2243A
initial_creation_type: input
source_metadata:
  id: ''
  title: Bodhisatvapiṭaka
  language: English
  author: ''
created_at: '2022-02-17T10:27:08.937998'
last_modified_at: '2022-02-17T10:27:08.938000'
