id:
  P9AE44348:
    type: origin_type
    relation: translation
    language: Sanskrit
  P5A3433D2:
    type: origin_type
    relation: translation
    language: Chinese
  PC71799C6:
    type: origin_type
    relation: translation
    language: Chinese
  PC2C46A3C:
    type: origin_type
    relation: translation
    language: Tibetan
  P042C0D39:
    type: origin_type
    relation: translation
    language: Tibetan
  P6667381E:
    type: origin_type
    relation: translation
    language: English
title: 'Chapter 9: Vīryapāramitā'
type: translation
source_metadata:
  language:
  - Chinese
  - Tibetan
  - Sanskrit
  - English
